<div class="btn-group">
    <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='edit' id=$row.id}" title="Edit"><i class="icon-pencil"></i></a>
    <a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' {if $resellerMode && ( $row.id || $row.id )}data-related="1"{/if} data-type="{$row.type}" href="{genUrl module=$module controller=$controller action='delete' id=$row.id}" title="Delete"><i class="icon-trash"></i></a>
</div>
