<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Action<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{genUrl controller="static" action="regeneratemrtg"}">生成MRTG配置文件</a>
        </li>


        <li>
            <a href="{genUrl controller="static" action="example"}">采集MAC地址(under build..)</a>
        </li>



        {* PLEASE LEAVE THIS SOMEWHERE!  IT'S ONLY FAIR INEX GETS SOME CREDIT :D *}
        <li class="divider"></li>
        <li>
            <a href="{genUrl controller="index" action="about"}">Docker操作</a>
        </li>
    </ul>
</li>
