<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Action<b class="caret"></b></a>
    <ul class="dropdown-menu">

        <li>
            <a href="{genUrl controller="noc" action="regeneratemrtg"}">生成MRTG配置文件</a>
        </li>


        <li>
            <a href="{genUrl controller="batch-ping" action="list"}">BatchPing(Underbuild...)</a>
        </li>




        <li>
            <a href="{genUrl controller="noc" action="refreshmac"}">采集MAC地址</a>
        </li>

        <li>
            <a href="{genUrl controller="static" action="example"}">Feature1(under build..)</a>
        </li>


        <li>
            <a href="{genUrl controller="static" action="example"}">Feature2(under build..)</a>
        </li>



        <li>
            <a href="{genUrl controller="static" action="example"}">Feature3(under build..)</a>
        </li>





        {* PLEASE LEAVE THIS SOMEWHERE!  IT'S ONLY FAIR INEX GETS SOME CREDIT :D *}
        <li class="divider"></li>

        <li>
            <a href="{genUrl controller="noc" action="docker"}">Docker操作</a>
        </li>
        
    </ul>
</li>
