<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * A_biz_type
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class A_biz_type extends EntityRepository
{
}
