<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * A_ip_biz
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class A_ip_biz extends EntityRepository
{
}
