<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * BatchPing
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchPing extends EntityRepository
{
}
