<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Cust_biz
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cust_biz extends EntityRepository
{
}
