<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Qq_iplist_diff
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Qq_iplist_diff extends EntityRepository
{
}
