{tmplinclude file="header.phtml"}

{if isset( $user ) and $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Action <span class="divider">/</span>
        </li>
        <li class="active">
            MRTG
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Example Documenation Page</h1>
        </div>
{/if}


<p>


点击按钮,重新生成MRTG的配置文件:&nbsp/ixpdata/mrtgcfg/mrtg.cfg

<br/><br/>

命令行:&nbsp; /opt/ixpmanager/bin/ixptool.php -a statistics-cli.gen-mrtg-conf
<br/><br/>
<input class="btn"  id="recreate_mrtg_cfg" value="Submit" type="submit">

<br/>

<pre><div id="mrtg_file"  class="well well-lg"></div></pre>

</p>


{if not isset( $user ) or $user->getPrivs() neq 3}
    </div>
{/if}
<script>{tmplinclude file="static/js/mrtg.js"}</script>
{tmplinclude file="footer.phtml"}
