<?php /* Smarty version Smarty-3.1.19-dev, created on 2017-02-23 04:35:22
         compiled from "/opt/ixpmanager/application/views/statistics-cli/mrtg/header.cfg" */ ?>
<?php /*%%SmartyHeaderCode:46552011158ae668ad9ff87-38912104%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'f331439f2740846dfd4fa3e0241305227a6bc147' => 
    array (
      0 => '/opt/ixpmanager/application/views/statistics-cli/mrtg/header.cfg',
      1 => 1487821144,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '46552011158ae668ad9ff87-38912104',
  'function' => 
  array (
  ),
  'variables' => 
  array (
    'options' => 0,
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.19-dev',
  'unifunc' => 'content_58ae668adb6165_77161962',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_58ae668adb6165_77161962')) {function content_58ae668adb6165_77161962($_smarty_tpl) {?><?php if (!is_callable('smarty_modifier_date_format')) include '/opt/ixpmanager/application/../vendor/smarty/smarty/libs/plugins/modifier.date_format.php';
?>
#
# IXP Manager MRTG configuration file
#
# Copyright (C) 2009-<?php echo smarty_modifier_date_format(time(),'Y');?>
 Internet Neutral Exchange Association Company Limited By Guarantee.
# All Rights Reserved.
# 
# This file is part of IXP Manager.
# 
# IXP Manager is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, version v2.0 of the License.
# 
# IXP Manager is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
# 
# You should have received a copy of the GNU General Public License v2.0
# along with IXP Manager.  If not, see:
# 
# http://www.gnu.org/licenses/gpl-2.0.html


### DO NOT EDIT THIS FILE - IT IS AUTOMATICALLY GENERATED
###
### LAST GENERATION: <?php echo smarty_modifier_date_format(time(),'Y-m-d H:i:s');?>



### Global Config Options
WorkDir: <?php echo $_smarty_tpl->tpl_vars['options']->value['mrtg']['conf']['workdir'];?>

RunAsDaemon:Yes
Interval:5

IconDir: /images/

### Global Defaults
#  to get bits instead of bytes and graphs growing to the right
Options[_]: growright, bits
WithPeak[_]: ym
PageTop[_]: <h1><?php echo $_smarty_tpl->tpl_vars['options']->value['identity']['orgname'];?>
 Traffic Analysis</h1>
PageFoot[_]:  <table border=0 cellspacing=0 cellpadding=0 width=476>
  <tr valign=top>
   <td align=left style="font: Arial,Helvetica; size: 80%">
     &copy; 2007-<?php echo smarty_modifier_date_format(time(),'Y');?>
 <a href="http://www.inex.ie/">Internet Neutral Exchange Association Company Limited By Guarantee</a>.
     All rights Reserved.
   </td>
   <td width=10>&nbsp;</td>
   <td align=right style="font: Arial,Helvetica; size: 80%">
     Generated by <a href="https://github.com/inex/IXP-Manager">IXP Manager</a> at <?php echo smarty_modifier_date_format(time(),'Y-m-d H:i:s');?>
.
   </td>
  </tr>
 </table>

<?php }} ?>
