<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Ticket extends \Entities\Ticket implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setSubIp($subIp)
    {
        $this->__load();
        return parent::setSubIp($subIp);
    }

    public function getSubIp()
    {
        $this->__load();
        return parent::getSubIp();
    }

    public function setMsg($msg)
    {
        $this->__load();
        return parent::setMsg($msg);
    }

    public function getMsg()
    {
        $this->__load();
        return parent::getMsg();
    }

    public function setReason($reason)
    {
        $this->__load();
        return parent::setReason($reason);
    }

    public function getReason()
    {
        $this->__load();
        return parent::getReason();
    }

    public function setMemo($memo)
    {
        $this->__load();
        return parent::setMemo($memo);
    }

    public function getMemo()
    {
        $this->__load();
        return parent::getMemo();
    }

    public function setIssuedate($issuedate)
    {
        $this->__load();
        return parent::setIssuedate($issuedate);
    }

    public function getIssuedate()
    {
        $this->__load();
        return parent::getIssuedate();
    }

    public function setFixed($fixed)
    {
        $this->__load();
        return parent::setFixed($fixed);
    }

    public function getFixed()
    {
        $this->__load();
        return parent::getFixed();
    }

    public function setFixedby($fixedby)
    {
        $this->__load();
        return parent::setFixedby($fixedby);
    }

    public function getFixedby()
    {
        $this->__load();
        return parent::getFixedby();
    }

    public function setRaisedby($raisedby)
    {
        $this->__load();
        return parent::setRaisedby($raisedby);
    }

    public function getRaisedby()
    {
        $this->__load();
        return parent::getRaisedby();
    }

    public function setCustrelate($custrelate)
    {
        $this->__load();
        return parent::setCustrelate($custrelate);
    }

    public function getCustrelate()
    {
        $this->__load();
        return parent::getCustrelate();
    }

    public function setCustnamerelate($custnamerelate)
    {
        $this->__load();
        return parent::setCustnamerelate($custnamerelate);
    }

    public function getCustnamerelate()
    {
        $this->__load();
        return parent::getCustnamerelate();
    }

    public function setEventId($eventId)
    {
        $this->__load();
        return parent::setEventId($eventId);
    }

    public function getEventId()
    {
        $this->__load();
        return parent::getEventId();
    }

    public function setRtDiff($rtDiff)
    {
        $this->__load();
        return parent::setRtDiff($rtDiff);
    }

    public function getRtDiff()
    {
        $this->__load();
        return parent::getRtDiff();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'sub_ip', 'msg', 'reason', 'memo', 'issuedate', 'fixed', 'fixedby', 'raisedby', 'custrelate', 'custnamerelate', 'event_id', 'rt_diff', 'price', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}