{assign var=keys value='/,\s*/'|preg_split:'Bits,Packets,Bytes'}
{assign var=vals value='/,\s*/'|preg_split:'bits,pkts,bytes'}
{assign var=categories value=$keys|@array_combine:$vals}


{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq USER::AUTH_SUPERUSER}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='statistics' action='members'}">Statistics</a> <span class="divider">/</span>
        </li>
        <li>
             <a href="{genUrl controller="customer" action="overview" id=$cust->getId()}">{$cust->getName()}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Peer to Peer Statistics
            (
             {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}
             {if isset( $period )}
                /
                 {foreach from=$periods key=cname item=cvalue}{if $period eq $cvalue}{$cname}{/if}{/foreach}
             {/if}
            )
        </li>
        <li class="pull-right"  style="margin-top: -6px;">
            <div class="btn-toolbar" style="display: inline;">
                <a class="btn btn-small" href="{genUrl controller="statistics" action="member" shortname=$cust->getShortname()}">
                    Statistics Overview
                </a>
            </div>
        </li>
        
    </ul>
    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>IXP Peer to Peer Statistics :: {$cust->getName()}</h1>
        </div>
{/if}

<p>
<form action="{genUrl controller="statistics" action="p2p"}{if $user->getPrivs() eq USER::AUTH_SUPERUSER}/shortname/{$cust->getShortname()}{/if}" method="post">
<table>
<tr>
    {if $multiIXP}
      
    {else}
        <input type="hidden" name="ixp" value="{$ixp->getId()}" />
    {/if}
    
    <td valign="middle"><strong>Network:</strong></td>
    <td>
        &nbsp;
        <select name="svli" style="width: 200px;" class="chzn-select">
            {foreach $srcVlis as $id => $vli}
                <option value="{$id}" {if $srcVli eq $vli}selected="selected"{/if}>
                    {$vli->getVlan()->getName()}
                </option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Graph Type:</strong></td>
    <td>
        &nbsp;
        <select name="category" style="width: 100px;" class="chzn-select">
            {foreach from=$categories key=cname item=cvalue}
                <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Period:</strong></td>
    <td>
        &nbsp;
        <select name="period" style="width: 100px;" class="chzn-select">
            {foreach from=$periods key=cname item=cvalue}
                <option value="{$cvalue}" {if $period eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Protocol:</strong></td>
    <td>
        &nbsp;
        <select name="proto" style="width: 100px;" class="chzn-select">
            {foreach from=$protocols key=pname item=pvalue}
                <option value="{$pvalue}" {if $proto eq $pvalue}selected="selected"{/if}>{$pname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle">
        <input class="btn" type="submit" value="ip2ip_Submit &raquo;" />
    </td>
    </tr>
</table>
</form>
</p>



<h1>{$src_mac}</h1>


<div class="row-fluid">


{foreach $ip_related as $one_ip}

    {$one_ip}


    <h5>
                    {genMrtgIp2ipImgUrl
                                ixp=$ixp->getId()
                                shortname=$cust->getShortname()
                                svli=$srcVli->getId()
                                dvli=0
                                category=$category
                                src_mac=$src_mac
                                dst_ip=$one_ip
                                period=$period
                                proto=$proto}

                                </h5>



{/foreach}    

{assign var='count' value=0}
{if $user->getPrivs() eq USER::AUTH_SUPERUSER}

    {foreach $dstVlis as $dvli}

        <div class="span3">
            <div class="well">
                <h4 style="vertical-align: middle">
                    {$dvli->getVirtualInterface()->getCustomer()->getName()}
                </h4>
    
                <p>
                    <br />
                    <h5>
                    {genMrtgIp2ipImgUrl
                                ixp=$ixp->getId()
                                shortname=$cust->getShortname()
                                svli=$srcVli->getId()
                                dvli=$dvli->getId()
                                category=$category
                                src_mac=$src_mac
                                period=$period
                                proto=$proto}

                                </h5>



                    <a href="{genUrl controller="statistics" action="ip2ip"
                            ixp=$ixp->getId()
                            shortname=$cust->getShortname()
                            svli=$srcVli->getId()
                            dvli=$dvli->getId()
                            category=$category
                            period=$period
                            proto=$proto}">
                        <img
                            src="{genMrtgIp2ipImgUrl
                                ixp=$ixp->getId()
                                shortname=$cust->getShortname()
                                svli=$srcVli->getId()
                                dvli=$dvli->getId()
                                category=$category
                                period=$period
                                proto=$proto}"
                            width="300"
                        />
                    </a>
                </p>
            </div>
        </div>
    
        {assign var='count' value=$count+1}
    
        {if $count%4 eq 0}
            </div><br /><div class="row-fluid">
        {/if}
    {/foreach}
    
    {if $count%4 neq 0}
        <div class="span3"></div>
        {assign var='count' value=$count+1}
        {if $count%4 neq 0}
            <div class="span3"></div>
            {assign var='count' value=$count+1}
            {if $count%4 neq 0}
                <div class="span3"></div>
                {assign var='count' value=$count+1}
            {/if}
        {/if}
    {/if}
    
    
{else}
    
{/if}
    
</div>

</div>

{tmplinclude file="footer.phtml"}