{assign var=keys value='/,\s*/'|preg_split:'Bits,Packets,Bytes'}
{assign var=vals value='/,\s*/'|preg_split:'bits,pkts,bytes'}
{assign var=categories value=$keys|@array_combine:$vals}


{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq USER::AUTH_SUPERUSER}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='statistics' action='members'}">Statistics</a> <span class="divider">/</span>
        </li>
        <li>
             <a href="{genUrl controller="customer" action="overview" id=$cust->getId()}">{$cust->getName()}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Peer to Peer Statistics
            (
             {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}
             {if isset( $period )}
                /
                 {foreach from=$periods key=cname item=cvalue}{if $period eq $cvalue}{$cname}{/if}{/foreach}
             {/if}
            )
        </li>
        <li class="pull-right"  style="margin-top: -6px;">
            <div class="btn-toolbar" style="display: inline;">
                <a class="btn btn-small" href="{genUrl controller="statistics" action="member" shortname=$cust->getShortname()}">
                    Statistics Overview
                </a>
            </div>
        </li>
        
    </ul>
    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>IXP Peer to Peer Statistics :: {$cust->getName()}</h1>
        </div>
{/if}

<p>
<form action="{genUrl controller="statistics" action="ip2ip"}{if $user->getPrivs() eq USER::AUTH_SUPERUSER}/shortname/{$cust->getShortname()}{/if}" method="post">
<table>
<tr>
    {if $multiIXP}
      
    {else}
        <input type="hidden" name="ixp" value="{$ixp->getId()}" />
    {/if}
    
    <td valign="middle"><strong>Network:</strong></td>
    <td>
        &nbsp;
       

    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Graph Type:</strong></td>
    <td>
        &nbsp;
        <select name="category" style="width: 100px;" class="chzn-select">
            {foreach from=$categories key=cname item=cvalue}
                <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Period:</strong></td>
    <td>
        &nbsp;
        <select name="period" style="width: 100px;" class="chzn-select">
            {foreach from=$periods key=cname item=cvalue}
                <option value="{$cvalue}" {if $period eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Protocol:</strong></td>
    <td>
        &nbsp;
        <select name="proto" style="width: 100px;" class="chzn-select">
            {foreach from=$protocols key=pname item=pvalue}
                <option value="{$pvalue}" {if $proto eq $pvalue}selected="selected"{/if}>{$pname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle">
        <input class="btn" type="submit" value="ip2ip_Submit &raquo;" />
    </td>
    </tr>
</table>
</form>
</p>


<div class="row-fluid">
 
{assign var='count' value=0}
 
     {foreach $tag_related as $one_ip}


                                

       <div class="span3" style="width: 550px;">
            <div class="well">
             <h5>{$one_ip['poolname']}<-->{$one_ip['ctag']}|/ixpdata/rrd/ip2ip/{$one_ip['poolmac']}/{$src_mac}/{$one_ip['etag']}</h5>
                <p>
                    <br />
                                
                      
                     <a href="#">
                                 

                     {* ./inex-smarty/functions/function.genMrtgIp2ipImgUrl.php *}

                
                        <img
                            src="{genMrtgIp2ipImgUrl
                                ixp=$ixp->getId()
                                shortname=$cust->getShortname()
                                category=$category
                                poolmac=$one_ip['poolmac']
                                src_mac=$src_mac
                                etag=$one_ip['etag']
                                period=$period
                                proto=$proto}"
                            width="600"
                        />
                    </a>
                      
                </p>
            </div>

        </div>
    
        {assign var='count' value=$count+1}
    
        {if $count%2 eq 0}
            </div><br /><div class="row-fluid">
        {/if}
    {/foreach}
 
    
    {if $count%2 neq 0}
        <div class="span3"></div>
        {assign var='count' value=$count+1}
        {if $count%2 neq 0}
            <div class="span3"></div>
            {assign var='count' value=$count+1}
            {if $count%2 neq 0}
                <div class="span3"></div>
                {assign var='count' value=$count+1}
            {/if}
        {/if}
    {/if}
    
    
 
</div>

</div>

{tmplinclude file="footer.phtml"}