{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller="customer" action="list"}">Customers</a> <span class="divider">/</span>
    </li>
     <li>
        <span>P2P表格</span>
    </li>
</ul>

<div>
<div>
     
     
<div class="row-fluid">
 
{assign var='count' value=0}
    
    {if $count%2 neq 0}
        <div class="span3"></div>
        {assign var='count' value=$count+1}
        {if $count%2 neq 0}
            <div class="span3"></div>
            {assign var='count' value=$count+1}
            {if $count%2 neq 0}
                <div class="span3"></div>
                {assign var='count' value=$count+1}
            {/if}
        {/if}
    {/if}
</div>


     {foreach $rows as $one_cust}

     {if 'p2p'|array_key_exists:$one_cust}

       <div class="span3" style="width:530px;">
            <div class="well">
             <h4>{$one_cust['name']} </h4>
                
             <table class="table table-bordered">
                  <tr> 
                   <td>客户名称</td>
                   <td>In</td>
                   <td>Out</td>
                   <td>In+Out</td>
                </tr>

               {foreach $one_cust['p2p'] as $one_p2p}

                <tr> 
                   <td>{$one_p2p['dstname']}</td>
                  
                   <td>{math format="%.2f" equation="(x/rate)" x=$one_p2p['traffic_in']   rate=80*1024   }</td>
                   <td>{math format="%.2f" equation="(x/rate)" x=$one_p2p['traffic_out']  rate=80*1024   }</td>
                   <td>{math format="%.2f" equation="(x/rate)" x=$one_p2p['traffic_avg']  rate=80*1024   }</td>
                  
                  

                </tr>
               {/foreach}         
             </table>
            </div>
     {/if}
        </div>
    {/foreach}

</div>

<table>
<tr>
    <td valign="middle"><input type="text" name="day" value="{$day->format( 'Y-m-d' )}" size="10" maxlength="10" /></td>
</tr>
</table>

 
</p>


</div>
 
 
{tmplinclude file="footer.phtml"}